all:	main.py
	cp main.py run
	chmod +x run
	cp read_student_data.py read_student_data
	chmod +x read_student_data
	cp translation.py translation
	chmod +x translation
	cp code_html.py code_html
	chmod +x code_html
	cp send_email.py send_email
	chmod +x send_email
	cp code_jason.py code_jason
	chmod +x code_jason

clean:	
	($RM) test

